---
- name: get user default hostgroup
  get_proxysql_hostgroup: {}

- name: proxysql all users
  set_fact:
    proxysql_all_users: "{{ all_users|default([]) + hostvars[item]['pillar']['mysql_user']['app'] }}"
  with_items: "{{ pillar.mha_setting.all_server_list }}"

- name: proxysql set users
  proxysql_mysql_users:
    login_user: "{{ pillar.proxysql_common.admin_user }}"
    login_password: "{{ pillar.proxysql_common.admin_password }}"
    username: "{{ item.name }}"
    password: "{{ item.password }}"
    default_hostgroup: "{{ pillar.proxysql_hostgroup }}"
    fast_forward: False
    state: present
  with_items: "{{ proxysql_all_users }}"
