---
- name: check id_rsa exists
  stat:
    path: /root/.ssh/id_rsa.pub
  register: id_rsa

- name: ssh keygen
  command: ssh-keygen -q -t rsa -N "" -f /root/.ssh/id_rsa
  when: id_rsa.stat.exists == False

- name: get ssh pub key
  shell: "sshpass -p '{{ hostvars[item]['ansible_ssh_pass'] }}' ssh root@{{ hostvars[item]['ansible_ssh_host'] }} cat /root/.ssh/id_rsa.pub"
  register: key_list
  with_items: "{{ pillar.mha_setting.all_server_list }}"
  ignore_errors: yes

- name: set authorized key took from file
  authorized_key:
    user: root
    state: present
    key: "{{ item.stdout }}"
  with_items: "{{ key_list.results }}"
