---
- name: Create terraform dir if it does not exist
  file:
    path: "{{ pillar.terraform.root_path }}/inventory/azure"
    state: directory
    mode:  0755

- name: azure credentials
  template:
    src: auth.tf.j2
    dest: "{{ pillar.terraform.root_path }}/inventory/azure/azure_auth.tf"
    mode: 0644
