---
- name: crontab
  hosts: all
  gather_facts: False
  external_task_id: 7e535817-a5f2-47af-b17d-5340315aba35
  tasks:
    - name: set crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: absent

    - name: query crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: query
      register: crontab

    - name: Record crontab result
      ara_record:
        key: "mybak_"
        value: ""
