---
- name: crontab
  hosts: all
  gather_facts: False
  external_task_id: 5af47196-58f1-4f03-b398-47a27d5c841d
  tasks:
    - name: set crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: absent

    - name: query crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: query
      register: crontab

    - name: Record crontab result
      ara_record:
        key: "mybak_{{ inventory_hostname }}"
        value: "{{ crontab }}"

