---
- name: crontab
  hosts: all
  gather_facts: False
  external_task_id: 2851a4a3-bc31-4837-aadc-9e504060a610
  tasks:
    - name: set crontab
      mycron:
        name: "MySQL Backup Scheduler"
        minute: "2"
        hour: "23"
        day: "*"
        month: "*"
        weekday: "*"
        job:  "/dbbackup/pyxbackup cron"
        state: present

    - name: query crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: query
      register: crontab

    - name: Record crontab result
      ara_record:
        key: "mybak_{{ inventory_hostname }}"
        value: "{{ crontab }}"

