---
- name: crontab
  hosts: all
  gather_facts: False
  external_task_id: abefd62e-c2e5-4cc5-9cb8-2d7709d2611a
  tasks:
    - name: query crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: query
      register: crontab

    - name: Record crontab result
      ara_record:
        key: "mybak_{{ inventory_hostname }}"
        value: "{{ crontab }}"

