---
- name: crontab
  hosts: all
  gather_facts: False
  external_task_id: 685ffc33-a812-4b09-871b-20b95c3a4738
  tasks:
    - name: query crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: query
      register: crontab

    - name: Record crontab result
      ara_record:
        key: "mybak_{{ inventory_hostname }}"
        value: "{{ crontab }}"

