---
- name: crontab
  hosts: all
  gather_facts: False
  external_task_id: e0f4a769-280b-4a13-bbc6-f9d1b656126b
  tasks:
    - name: query crontab
      mycron:
        name: "MySQL Backup Scheduler"
        state: query
      register: crontab

    - name: Record crontab result
      ara_record:
        key: "mybak_{{ inventory_hostname }}"
        value: "{{ crontab }}"

