---
- name: mysql dba account
  hosts: prod
  gather_facts: False
  pre_tasks:
    - pillar: {}    
  tasks:
    - name: install mysql python module
      yum: 
        name: MySQL-python
        state: installed
      environment:
        http_proxy: http://{{ pillar.proxy.proxy }}
        https_proxy: https://{{ pillar.proxy.proxy }}

    - name: show script for create mysql user.
      debug:
        msg: "GRANT ALL PRIVILEGES ON *.* TO '{{ item.name }}'@'{{ item.host | default('localhost') }}' IDENTIFIED BY PASSWORD '{{ item.password }}' WITH GRANT OPTION;"
      when: item.state is not defined or item.state == 'present'
      loop: "{{ pillar.mysql_user.dba }}"

    - name: show script for drop mysql user.
      debug:
        msg: "DROP USER '{{ item.name }}'@'{{ item.host | default('localhost') }}';"
      when: item.state is defined and item.state == 'absent'
      loop: "{{ pillar.mysql_user.dba }}"
