---
- name: mysql dba account
  hosts: mysql
  gather_facts: True
  pre_tasks:
    - pillar: {}    
  tasks:
    - name: Ensure MySQL dba users are present.
      mysql_user:
        login_user: root
#        login_password: root123
        login_password: "{{ pillar.mysql_root.password }}"
        login_unix_socket: "{{ pillar.mysql_common.socket }}"
#        login_host: "10.42.231.79"
        name: "{{ item.name }}"
        host: "{{ item.host | default('localhost') }}"
        password: "{{ item.password }}"
        encrypted: "{{ item.encrypted }}"
        priv: "{{ item.priv | default('*.*:USAGE') }}"
        sql_log_bin: yes
        state: "{{ item.state | default('present') }}"
        append_privs: "{{ item.append_privs | default('no') }}"
      loop: "{{ pillar.mysql_user.dba }}"
