---
- name: reboot
  hosts: all
  tasks:
    - name: reboot
      shell: shutdown -r now
      async: 0
      poll: 0 

    # Now we will run a local 'ansible -m ping' on this host until it returns.
    - name: wait for system reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15

    - name: uptime
      shell: uptime
