---
- name: with dict
  hosts: shell
  gather_facts: True
  tasks:
    - name: repo file
      debug:
        msg: "name={{ pillar.mysql_common.software_dir }}/{{ pillar.mysql_common_pkg | join(' '+pillar.mysql_common.software_dir+'/') }} state=installed"

    - name: create partition
      debug:
        msg: "device: {{ item[1].device }}, number: {{ item[1].number }}"
      with_nested:
        - ['/dev/sda', 'dev/sdb']
        - "{{ pillar.parted }}"
