---
- name: with dict
  hosts: shell
  gather_facts: True
  pre_tasks:
    - pillar: {} 
  tasks:
    - name: repo file
      debug:
        var: item.key
      with_dict: "{{ pillar.repo_file }}"

    - name: create partition
      debug:
        msg: "device: {{ item[1].device }}, number: {{ item[1].number }}"
      with_nested:
        - ['/dev/sda', 'dev/sdb']
        - "{{ pillar.parted }}"
