---
- name: adjust sysctl parameter for lvs
  sysctl: 
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: "{{ pillar.lvs_sysctl.server }}"
  ignore_errors: yes
