---
- name: Create mmm software dir if it does not exist
  file:
    path: "{{ pillar.mmm_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to mmm software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.mmm_common.software_dir }}/{{ item }}"
    mode: 0644
    force: yes
  loop: "{{ pillar.mmm_pkg }}"

- name: Ensure mmm packages are installed.
  yum: "name={{ pillar.mmm_common.software_dir }}/{{ pillar.mmm_pkg | join(', '+pillar.mmm_common.software_dir+'/') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure mmm packages are installed.
  yum: "name={{ pillar.mmm_common.software_dir }}/{{ pillar.mmm_pkg | join(', '+pillar.mmm_common.software_dir+'/') }} state=installed"
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: load profile in mmm agent
  lineinfile:
    path: /etc/init.d/mysql-mmm-agent
    state: present
    regexp: ". /etc/profile"
    line: ". /etc/profile"
    insertafter: '. /etc/default/mysql-mmm-agent'
  when: pillar.myhost.os_ver == 6
