pacemaker_group:
  default:
    stella_cluster:
      property:
        stonith-enabled: "false"
        no-quorum-policy: "ignore"
      resource:
        - id: mysql_vip
          type: "IPaddr2"
          options:
            ip: 10.42.231.10
            cidr_netmask: 24
            nic: eth0
          op:
            - action: monitor
              options:
                interval: 5s
        - id: mha_srv
          type: "systemd:mha@stella"
          op:
            - action: monitor
              options:
                interval: 5s
      nodes:
        - mysql01-allan.sjc1
        - mysql02-allan.sjc1
    mha_cluster:
      property:
        stonith-enabled: "false"
        no-quorum-policy: "ignore"
      resource:
        - id: mysql_vip
          type: "IPaddr2"
          options:
            ip: 10.42.32.236
            cidr_netmask: 24
            nic: eth0
          op:
            - action: monitor
              options:
                interval: 5s
        - id: mha_srv
          type: "systemd:mha@mygroup"
          op:
            - action: monitor
              options:
                interval: 5s
      nodes:
        - dcs-t-mysqlmha-managernode1.sjc1
        - dcs-t-mysqlmha-managernode2.sjc1
