---
- name: Create pmm software dir if it does not exist
  file:
    path: "{{ pillar.pmm_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy pmm rpm to pmm software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.pmm_common.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  loop: "{{ pillar.pmm_admin_pkg }}"

- name: Ensure PMM packages are installed.
  yum: "name={{ pillar.pmm_common.software_dir }}/{{ pillar.pmm_admin_pkg | join(', '+pillar.pmm_common.software_dir+'/') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure PMM packages are installed.
  yum: "name={{ pillar.pmm_common.software_dir }}/{{ pillar.pmm_admin_pkg | join(', '+pillar.pmm_common.software_dir+'/') }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy'"
