---
- name: Create mysql software dir if it does not exist
  file:
    path: "{{ pillar.mysql_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to mysql software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.mysql_common.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  loop: "{{ pillar.mysql_common_pkg }}"

- name: Ensure MySQL common packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ pillar.mysql_common_pkg | join(', '+pillar.mysql_common.software_dir+'/') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy' and (pillar.mysql_common_pkg | length) > 0"

- name: Ensure MySQL common packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ pillar.mysql_common_pkg | join(', '+pillar.mysql_common.software_dir+'/') }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy' and (pillar.mysql_common_pkg | length) > 0"
