---
- name: Create mysql software dir if it does not exist
  file:
    path: "{{ pillar.mysql_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to mysql software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.mysql_common.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  with_items: "{{ pillar.mysql_common_pkg }}"

- name: Ensure MySQL common packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ item }} state=installed"
  with_items: "{{ pillar.mysql_common_pkg }}"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure MySQL common packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ item }} state=installed"
  with_items: "{{ pillar.mysql_common_pkg }}"
  when: "pillar.proxy.proxy == 'no_proxy'"
