---
- name: check MySQL version
  include_tasks: check_version.yml

- name: my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ pillar.mysql_common.config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: change owner for datadir
  file:
    path: "{{ pillar.mysql_common.data_dir }}"
    owner: mysql
    group: mysql
    recurse: yes

- name: Ensure MySQL is enabled on boot.
  service: "name={{ pillar.mysql_daemon.mysql_daemon }} enabled=yes"

