---
- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_version

- name: generate mysql config
  gen_mysql_cnf:
    mysql_version: "{{ mysql_version }}"

- name: my.cnf
  template:
    src: my.cnf.j2
    dest: "{{ pillar.mysql_common.config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Ensure MySQL is started and enabled on boot.
  service: "name={{ item }} state=started enabled=yes"
  with_items: "{{ pillar.mysql_cnf.service_list }}"

