---
- name: Ensure MySQL databases are present.
  mysql_db:
    login_user: root
    login_password: "{{ pillar.mysql_common.password }}"
    login_unix_socket: "{{ pillar.mysql_common.socket }}"
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: "{{ pillar.mysql_database }}"
