---
- name: copy mysql scripts to remote
  copy:
    src: "{{ item.sql }}"
    dest: "/tmp/{{ item.sql }}"
    owner: mysql
    group: mysql
    mode: 0644
    force: no
  loop: "{{ pillar.mysql_run_script }}"

- name: import mysql scripts
  mysql_db:
    login_user: root
    login_password: "{{ pillar.mysql_root.password }}"
    login_unix_socket: "{{ pillar.mysql_common.socket }}"
    name: "{{ item.name }}"
    target: "/tmp/{{ item.sql }}"
    state: import
  loop: "{{ pillar.mysql_run_script }}"
