---
- name: copy mysql scripts to remote
  copy:
    src: "{{ item.sql }}"
    dest: "/tmp/{{ item.sql }}"
    owner: mysql
    group: mysql
    mode: 0644
    force: no
  with_items: "{{ pillar.mysql_run_script }}"

- name: import mysql scripts
  mysql_db:
    login_user: root
    login_password: "{{ pillar.mysql_common.password }}"
    login_unix_socket: "{{ item[0] }}"
    name: "{{ item[1].name }}"
    target: "/tmp/{{ item[1].sql }}"
    state: import
  with_nested:
    - "{{ pillar.mysql_cnf.socket_list }}"
    - "{{ pillar.mysql_run_script }}"
