---
- name: Create mysql data dir if it does not exist
  file:
    path: "{{ pillar.mysql_common.data_dir }}"
    state: directory
    owner: mysql
    group: mysql
    mode:  0755

- name: mysql install db single instance
  command: mysql_install_db
  become: true
  become_user: mysql
  when: '"5.6." in mysql_version.stdout'

- name: mysql install db single instance
  command: mysqld --initialize-insecure
  become: true
  become_user: mysql
  when: '"5.7." in mysql_version.stdout'

- name: Change owner for mysql data dir
  file:
    path: "{{ pillar.mysql_common.data_dir }}"
    owner: mysql
    group: mysql
    recurse: yes

- name: start MySQL
  service: "name={{ pillar.mysql_daemon.mysql_daemon }} state=started"

- name: mysql secure installation
  command: mysql -S {{ pillar.mysql_common.socket }} -NBe "{{ item }}"
  with_items: ["DELETE FROM mysql.user WHERE User=''", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "update mysql.user set password_expired='N' where user='root'", "flush privileges"]

- name: Remove MySQL test database.
  mysql_db:
    login_user: root
    login_unix_socket: "{{ pillar.mysql_common.socket }}"
    name: test
    state: absent

- name: Get list of hosts for the root user.
  command: "mysql -NBe \"SELECT Host FROM mysql.user WHERE User = 'root' ORDER BY (Host='localhost') ASC\""
  register: mysql_root_hosts

# Set root password
- name: Update MySQL root password for localhost root account
  shell: mysql -S {{ pillar.mysql_common.socket }} -NBe 'SET PASSWORD FOR "root"@"{{ item }}" = PASSWORD("{{ pillar.mysql_common.password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines | default([]) }}"
