---
- name: set mysql limits
  set_limits:
    limits_key: mysql_limits

- name: mysql_soft_nofile
  pam_limits:
    domain: "{{ item.name }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items: "{{ pillar.mysql_limits }}"
