---
- name: Copy plugin file to mysql plugin dir
  copy: 
    src: "{{ item.src }}-{{ pillar.mysql_version.main }}"
    dest: "{{ pillar.mysql_config.plugin_dir }}/{{ item.dest }}"
    mode: 0755
    force: no
  loop: "{{ pillar.mysql_plugin_file }}"
