---
- name: Create mysql software dir if it does not exist
  file:
    path: "{{ pillar.mysql_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to mysql software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.mysql_common.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  loop: "{{ pillar.mysql_local_pkg }}"

- name: Ensure MySQL local packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ pillar.mysql_local_pkg | join(', '+pillar.mysql_common.software_dir+'/') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy' and (pillar.mysql_local_pkg | length) > 0"

- name: Ensure MySQL local packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ pillar.mysql_local_pkg | join(', '+pillar.mysql_common.software_dir+'/') }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy' and (pillar.mysql_local_pkg | length) > 0"

- name: fix max num of process
  lineinfile:
    path: /usr/lib/systemd/system/{{ item[0] }}.service
    regexp: "^{{ item[1].property }}"
    line: "{{ item[1].property }}={{ item[1].value }}"
  with_nested:
    - [ "{{ pillar.mysql_daemon.mysql_daemon }}", "{{ pillar.mysql_daemon.mysql_daemon }}@"]
    - [{ property: 'LimitNOFILE', value: "{{ pillar.mysql_limits.mysql.nofile }}" }, { property: 'LimitNPROC', value: "{{ pillar.mysql_limits.mysql.nproc }}" }]
  when: pillar.myhost.os_ver == "7"

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes  
  when: pillar.myhost.os_ver == "7"

- name: Ensure MySQL is disabled on boot.
  service: "name={{ pillar.mysql_daemon.mysql_daemon }} enabled=no"
