---
- name: Create mysql software dir if it does not exist
  file:
    path: "{{ pillar.mysql_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to mysql software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.mysql_common.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  loop: "{{ pillar.mysql_local_pkg }}"

- name: Copy backup script to backup dir
  copy: 
    src: "pyxbackup"
    dest: "{{ pillar.mysql_backup.backup_root_dir }}/pyxbackup"
    mode: 0755
    force: no

- name: Ensure MySQL local packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ pillar.mysql_local_pkg | join(', '+pillar.mysql_common.software_dir+'/') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy' and (pillar.mysql_local_pkg | length) > 0"

- name: Ensure MySQL local packages are installed.
  yum: "name={{ pillar.mysql_common.software_dir }}/{{ pillar.mysql_local_pkg | join(', '+pillar.mysql_common.software_dir+'/') }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy' and (pillar.mysql_local_pkg | length) > 0"

- name: Ensure MySQL packages are installed.
  yum: "name={{ pillar.mysql_pkg | join(', ') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure MySQL packages are installed.
  yum: "name={{ pillar.mysql_pkg | join(', ') }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy'"

- name: fix max num of process
  lineinfile:
    dest: /usr/lib/systemd/system/{{ pillar.mysql_daemon.mysql_daemon }}.service
    regexp: "^{{ item.property }}"
    line: "{{ item.property }}={{ item.value }}"
  loop:
    - { property: 'LimitNOFILE', value: "{{ pillar.mysql_limits.mysql.nofile }}" }
    - { property: 'LimitNPROC', value: "{{ pillar.mysql_limits.mysql.nproc }}" }
  when: pillar.myhost.os_ver == "7"

- name: fix max num of process
  lineinfile:
    dest: /usr/lib/systemd/system/{{ pillar.mysql_daemon.mysql_daemon }}@.service
    regexp: "^{{ item.property }}"
    line: "{{ item.property }}={{ item.value }}"
  loop:
    - { property: 'LimitNOFILE', value: "{{ pillar.mysql_limits.mysql.nofile }}" }
    - { property: 'LimitNPROC', value: "{{ pillar.mysql_limits.mysql.nproc }}" }
  when: pillar.myhost.os_ver == "7"

- name: daemon-reload
  command: systemctl daemon-reload
  when: pillar.myhost.os_ver == "7"

- name: Ensure MySQL is disabled on boot.
  service: "name={{ pillar.mysql_daemon.mysql_daemon }} enabled=no"
