---
- name: Ensure pacemaker packages are installed.
  yum: "name={{ item }} state=installed"
  with_items: "{{ pillar.pacemaker_pkg }}"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure pacemaker packages are installed.
  yum: "name={{ item }} state=installed"
  with_items: "{{ pillar.pacemaker_pkg }}"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy == 'no_proxy'"
