---
- name: Ensure pacemaker packages are installed.
  yum: "name={{ pillar.pacemaker_pkg | join(', ') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure pacemaker packages are installed.
  yum: "name={{ pillar.pacemaker_pkg | join(', ') }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy'"
