---
- name: Ensure heartbeat packages are installed.
  yum: "name={{ pillar.heartbeat_pkg | join(', ') }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}    
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure heartbeat packages are installed.
  yum: "name={{ pillar.heartbeat_pkg | join(', ') }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy'"
