---
- name: check client file exists
  win_stat:
    path: "{{ pillar.mssql_common.software_folder }}\\{{ item.name }}"
  with_items: "{{ pillar.mssql_client.2017 }}"
  when: (pillar.mssql_client.2017 is defined)
  register: client_files

- name: download client file
  win_copy:
    src: "{{ item[1].name }}"
    dest: "{{ pillar.mssql_common.software_folder }}\\{{ item[1].name }}"
  when: (pillar.mssql_client.2017 is defined and not item[0].stat.exists)
  with_nested:
    - "{{ client_files.results }}"
    - "{{ pillar.mssql_client.2017 }}"

- name: install client
  win_package:
    path: "{{ pillar.mssql_common.software_folder }}\\{{ item.name }}"
    product_id: "{{ item.product_id }}"
    arguments: "{{ item.args }}"
    state: present
  with_items: "{{ pillar.mssql_client.2017 }}"
  when: (pillar.mssql_client.2017 is defined)

- name: check reboot require for client
  win_zreboot:
    state: present
  register: result_rs

- name: reboot server
  win_reboot:
  when: result_rs.reboot_required
