---
- name: add a powershell module
  win_psmodule:
    name: "{{ item }}"
    allow_clobber: True
    state: present
  loop: "{{ pillar.mssql_psmodule }}"

- name: set disk vars
  include_tasks: check_disk.yml

- name: check Auto Provision zip file
  win_stat:
    path: "{{ pillar.mssql_common.dba_folder }}\\Auto_Provision_SQLserver.zip"
  register: installer_file

- name: download Auto Provision zip file
  win_copy:
    src: Auto_Provision_SQLserver.zip
    dest: "{{ pillar.mssql_common.dba_folder }}\\Auto_Provision_SQLserver.zip"
  when: not installer_file.stat.exists
        
- name: unzip Auto Provision zip file
  win_unzip:   
    src: "{{ pillar.mssql_common.dba_folder }}\\Auto_Provision_SQLserver.zip"
    dest: "{{ pillar.mssql_common.dba_folder }}\\"

- name: Copy setup config file
  win_template:
    src: setup.conf.j2
    dest: "{{ pillar.mssql_common.dba_folder }}\\Auto_Provision_SQLserver\\setup.conf"
    
- name: run Auto Provision file
  win_command: "{{ pillar.mssql_common.dba_folder }}\\Auto_Provision_SQLserver\\setup.bat  {{ pillar.mssql_common.dba_folder }}\\Auto_Provision_SQLserver "
  when: not installer_file.stat.exists
