---
- name: set disk vars
  include_tasks: check_disk.yml

- name: copy create database powershell script
  win_template:
    src: create_database.ps1.j2
    dest: "{{ pillar.mssql_common.dba_folder }}\\create_database.ps1"

- name: run create database powershell script
  win_shell: "{{ pillar.mssql_common.dba_folder }}\\create_database.ps1  -databasename {{ item }}"
  loop: "{{ pillar.mssql_database }}"
