---
- name: set disk vars
  include_tasks: check_disk.yml

- name: Create DBA folder
  win_file:
    path: "{{ pillar.mssql_common.dba_folder }}"
    state: directory

- name: Create Software folder
  win_file:
    path: "{{ pillar.mssql_common.software_folder }}"
    state: directory

- name: check kb file exists
  win_stat:
    path: "{{ pillar.mssql_common.software_folder }}\\{{ item }}"
  loop: "{{ pillar.mssql_kb.2017 }}"
  when: (pillar.mssql_kb.2017 is defined)
  register: kb_files

- name: download kb file
  win_copy:
    src: "{{ item[1] }}"
    dest: "{{ pillar.mssql_common.software_folder }}\\{{ item[1] }}"
  when: (pillar.mssql_kb.2017 is defined and not item[0].stat.exists)
  with_nested:
    - "{{ kb_files.results }}"
    - "{{ pillar.mssql_kb.2017 }}"

- name: install kb
  win_hotfix:
    source: "{{ pillar.mssql_common.software_folder }}\\{{ item }}"
    state: present
  loop: "{{ pillar.mssql_kb.2017 }}"
  when: (pillar.mssql_kb.2017 is defined)

- name: reboot server
  win_zreboot:
    state: present
  register: result_rs

- name: check reboot require for kb
  win_reboot:
  when: result_rs.reboot_required

- name: check mssql iso
  win_stat:
    path: "{{ pillar.mssql_common.software_folder }}\\{{ pillar.mssql_server.2017[0].name }}"
  register: iso_file

- name: Copy mssql iso
  win_copy:
    src: "{{ pillar.mssql_server.2017[0].name }}"
    dest: "{{ pillar.mssql_common.software_folder }}\\{{ pillar.mssql_server.2017[0].name }}"
  when: not iso_file.stat.exists

- name: mounted iso file
  win_disk_image:
    image_path: "{{ pillar.mssql_common.software_folder }}\\{{ pillar.mssql_server.2017[0].name }}"
    state: present
  register: iso_mount
  notify: umount iso

- name: copy unattended config file
  win_template:
    src: "{{ pillar.mssql_server.2017[0].unattended }}.j2"
    dest: "{{ pillar.mssql_common.software_folder }}\\{{ pillar.mssql_server.2017[0].unattended }}"

- name: run sql server setup
  win_package:
    path: "{{ iso_mount.mount_path }}setup.exe"
    product_id: "{{ pillar.mssql_server.2017[0].product_id }}"
    arguments: "/Q /SQLSVCPASSWORD={{ pillar.mssql_password.svc_password }} /AGTSVCPASSWORD={{ pillar.mssql_password.agent_password }} /SAPWD={{ pillar.mssql_password.sa_password }} /ConfigurationFile={{ pillar.mssql_common.software_folder }}\\{{ pillar.mssql_server.2017[0].unattended }}"
    state: present

- name: umount iso
  win_disk_image:
    image_path: "{{ pillar.mssql_common.software_folder }}\\{{ pillar.mssql_server.2017[0].name }}"
    state: absent

- name: reboot server
  win_zreboot:
    state: present
  register: result_rs

- name: check reboot require for sqlserver install
  win_reboot:
  when: result_rs.reboot_required
