---
- name: check patch file exists
  win_stat:
    path: "{{ pillar.mssql_common.software_folder }}\\{{ item.name }}"
  with_items: "{{ pillar.mssql_patch.2017 }}"
  when: (pillar.mssql_patch.2017 is defined)
  register: patch_files

- name: download patch file
  win_copy:
    src: "{{ item[1].name }}"
    dest: "{{ pillar.mssql_common.software_folder }}\\{{ item[1].name }}"
  when: (pillar.mssql_patch.2017 is defined and not item[0].stat.exists)
  with_nested:
    - "{{ patch_files.results }}"
    - "{{ pillar.mssql_patch.2017 }}"

- name: install patch
  win_package:
    path: "{{ pillar.mssql_common.software_folder }}\\{{ item.name }}"
    product_id: "{{ item.product_id }}"
    arguments: "{{ item.args }}"
    state: present
  with_items: "{{ pillar.mssql_patch.2017 }}"
  when: (pillar.mssql_patch.2017 is defined)
  register: patch_install

- name: check reboot require for patch
  win_reboot:
  when: (patch_install.results is defined and True in patch_install.results)
