---
- name: check ifcfg-eth0 file exists
  stat:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
  register: ifcfg_eth0

- name: move network setting
  shell: "/bin/mv /etc/sysconfig/network-scripts/ifcfg-e* /etc/sysconfig/network-scripts/ifcfg-eth0"
  when: ifcfg_eth0.stat.exists == False

- name: check ifcfg-eth0 file exists
  stat:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
  register: ifcfg_eth0

- name: modify eth0 name
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^NAME=".*'
    replace: 'NAME=eth0'
  when: ifcfg_eth0.stat.exists

- name: modify eth0 device
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DEVICE=".*'
    replace: 'DEVICE=eth0'
  when: ifcfg_eth0.stat.exists
