---
- name: Ensure selinux Python libraries are installed.
  yum: "name={{ pillar.common_pkgs.selinux_pkg }} state=installed"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure selinux Python libraries are installed.
  yum: "name={{ pillar.common_pkgs.selinux_pkg }} state=installed"
  when: "pillar.proxy.proxy == 'no_proxy'"

- name: disable selinux
  selinux:
    state: disabled

- name: Ensure iptables is stopped and disabled on boot.
  service: "name={{ pillar.common_pkgs.firewall_srv }} state=stopped enabled=false"
  ignore_errors: true

- name: install common tool 
  yum: "name={{ item }} state=installed"
  with_items: "{{ pillar.common_tool_pkgs }}"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: install common tool 
  yum: "name={{ item }} state=installed"
  with_items: "{{ pillar.common_tool_pkgs }}"
  when: "pillar.proxy.proxy == 'no_proxy'"

- name: install python tool
  shell: "echo y | pip install {{ item }}"
  with_items: "{{ pillar.common_python_pkgs }}"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: install python tool
  shell: "echo y | pip install {{ item }}"
  with_items: "{{ pillar.common_python_pkgs }}"
  when: "pillar.proxy.proxy == 'no_proxy'"
