---
- name: generate ssh config
  gen_ssh_config:
    ssh_config_key: ssh_config

- name: ssh_config
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
