---
- name: add linux group
  group:
    name: "{{ item.username }}"
    gid: "{{ item.id }}"
    state: present
  loop: "{{ pillar.linux_accounts }}"

- name: add linux user
  user:
    name: "{{ item.username }}"
    group: "{{ item.username }}"
    uid: "{{ item.id }}"
    password: "{{ item.password }}"
  loop: "{{ pillar.linux_accounts }}"

- name: add user to sudoers file
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ item.username }}'
    line: '{{ item.username }}           ALL=(ALL)       NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  when: "{{ item.sudo }}"
  loop: "{{ pillar.linux_accounts }}"
