---
- name: get mysql log setting
  get_mysql_config:
    myhost: "{{ pillar.myhost }}"
  register: mysql_config

- name: check folder status
  stat:
    path: "{{ mysql_config.datadir }}"
  register: data_dir

- name: append nxlog to mysql group
  user:
    name: nxlog
    groups: nxlog, mysql
    append: yes

- name: check error log status
  stat:
    path: "{{ mysql_config.log_error }}"
  register: error_log

- name: change owner for error log file
  file:
    path: "{{ mysql_config.log_error }}"
    owner: mysql
    group: mysql
  when: error_log.stat.exists

- name: check slow log status
  stat:
    path: "{{ mysql_config.slow_query_log_file }}"
  register: slow_log

- name: change owner for slow log file
  file:
    path: "{{ mysql_config.slow_query_log_file }}"
    owner: mysql
    group: mysql
  when: slow_log.stat.exists

- name: check audit log status
  stat:
    path: "{{ mysql_config.audit_json_log_file }}"
  register: audit_log

- name: change owner for audit log file
  file:
    path: "{{ mysql_config.audit_json_log_file }}"
    owner: mysql
    group: mysql
  when: audit_log.stat.exists

- name: nxlog config
  template:
    src: nxlog.mysql.conf.j2
    dest: /etc/nxlog.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nxlog for linux
  when: data_dir.stat.exists
