---
- name: Create directory structure
  win_file:
    path: "{{ pillar.nxlog_common.win_software_dir }}"
    state: directory

- name: Copy a install file
  win_copy:
    src: "{{ item }}"
    dest: "{{ pillar.nxlog_common.win_software_dir }}\\{{ item }}"
  with_items: "{{ pillar.nxlog_win_pkg }}"

- name: Install an MSI file
  win_msi:
    path: "{{ pillar.nxlog_common.win_software_dir }}\\{{ item }}"
    state: present
    wait: true
  with_items: "{{ pillar.nxlog_win_pkg }}"
