---
- name: nxlog_pkg
  get_setting:
    myhost: "{{ myhost }}"
    setting: "{{ nxlog_pkg }}"
    extra_setting: {'check_osver': True }
    value_type: list
  delegate_to: 127.0.0.1
  register: nxlog_pkg

# Copy rpm to software dir 
- name: Create nxlog software dir if it does not exist
  file:
    path: "{{ nxlog_common.meta.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to nxlog software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ nxlog_common.meta.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  with_items: "{{ nxlog_pkg.meta }}"

- name: Ensure nxlog packages are installed.
  yum: "name={{ nxlog_common.meta.software_dir }}/{{ item }} state=installed"
  with_items: "{{ nxlog_pkg.meta }}"
  environment:
    http_proxy: http://{{ myhost.my_domain }}-prxy.sdi.trendnet.org:8080
    https_proxy: https://{{ myhost.my_domain }}-prxy.sdi.trendnet.org:8080

- name: Ensure nxlog is enabled on boot.
  service: "name=nxlog enabled=yes"
