---
# Copy rpm to software dir 
- name: Create nxlog software dir if it does not exist
  file:
    path: "{{ pillar.nxlog_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to nxlog software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.nxlog_common.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  loop: "{{ pillar.nxlog_pkg }}"

- name: Ensure nxlog packages are installed.
  yum: "name={{ pillar.nxlog_common.software_dir }}/{{ item }} state=installed"
  loop: "{{ pillar.nxlog_pkg }}"
  environment:
    http_proxy: http://{{ pillar.proxy.proxy }}
    https_proxy: http://{{ pillar.proxy.proxy }}
  when: "pillar.proxy.proxy != 'no_proxy'"

- name: Ensure nxlog packages are installed.
  yum: "name={{ pillar.nxlog_common.software_dir }}/{{ item }} state=installed"
  loop: "{{ pillar.nxlog_pkg }}"
  when: "pillar.proxy.proxy == 'no_proxy'"

- name: Ensure nxlog is enabled on boot.
  service: "name=nxlog enabled=yes"
