---
# Copy rpm to software dir 
- name: Create nxlog software dir if it does not exist
  file:
    path: "{{ pillar.nxlog_common.software_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: Copy rpm to nxlog software dir
  copy: 
    src: "{{ item }}"
    dest: "{{ pillar.nxlog_common.software_dir }}/{{ item }}"
    mode: 0644
    force: no
  with_items: "{{ pillar.nxlog_pkg }}"

- name: Ensure nxlog packages are installed.
  yum: "name={{ pillar.nxlog_common.software_dir }}/{{ item }} state=installed"
  with_items: "{{ pillar.nxlog_pkg }}"
  environment:
    http_proxy: http://{{ pillar.myhost.domain }}-prxy.sdi.trendnet.org:8080
    https_proxy: https://{{ pillar.myhost.domain }}-prxy.sdi.trendnet.org:8080

- name: Ensure nxlog is enabled on boot.
  service: "name=nxlog enabled=yes"
